DESIGN=MSS_SUBSYSTEM_sb_0
DESDIR=C:\Users\hbreslin\Desktop\Project Workspace\My projects\M2S090\M2S060\designer\MSS_SUBSYSTEM_sb_0
TARGET_DIR=C:\Users\hbreslin\Desktop\Project Workspace\My projects\M2S090\M2S060\designer\MSS_SUBSYSTEM_sb_0
FAM=SmartFusion2
DIE=PA4M6000_N
PACKAGE=fg484
PINRPT_BY_NAME=1
PINRPT_BY_NUMBER=1
BANK_REPORT=1
IOREG_REPORT=1
